### ISSUE TITLE
extract generates multiple copies of some objects

### ISSUE THREAD

**Issue by 4x4falcon** [TimSC/pgmap#1]
Using the following:

./extract --bbox=[151.202023,-33.8836877,151.2101126,-33.8768114] --out=sydney_centre.osm.gz

Generates multiple copies of the relation with id '964748'

Extract is available here:

http://freestreetmap.org/planet/extracts

In the sydney_centre extract it is duplicated 5 times.  In the australia.osm.gz extract it  is duplicated 14 times.

This is the only occurrence I have found yet of this happening.

The relation only appears once in the db_map  database.

**Comment by TimSC** [comment]
I'm not sure why this is happening. I'll look into it but I have not reproduced it yet - have you been modifying this area in the last month or so? 

You know your extract area is really long and thin? :)

**Comment by 4x4falcon** [comment]
No modifications by me in the last month.  This relation is from 2015 and has not been edited since.

I can not see any problems with the relation and it validates correctly.



It's the only one I've found for a whole of Australia extract and only picked it up when trying to add it to a mapnik database with osm2pgsql.



Typo on the bounding box :)

**Comment by TimSC** [comment]
@4x4falcon Does 721bb3b improve things?

**Comment by 4x4falcon** [comment]
Fixed no longer duplication of this relation.  Have not seen any others yet.
