### ISSUE TITLE
extract does not work on zero crossing longitude

### ISSUE THREAD

**Issue by 4x4falcon** [TimSC/pgmap#2]
Using the following:

./extract --bbox=[-1.0, 50.5, 1.0, 50.6] --out=test_-1.0_50.5_1.0_50.6.osm.gz

gives only the data in the bounding box 0.0,50.5,1.0,50.6 in the file

if using:

./extract --bbox=[1.0, 50.5, -1.0, 50.6] --out=test_-1.0_50.5_1.0_50.6.osm.gz

gives only the data in the bounding box -1.0, 50.5, 0.0, 50.6

So it will not give the complete bounding box when the box crosses 0deg longitude.

Bounding boxs are left,bottom,right,top in the first instance and right,bottom,left,top in the second instance.

I have not tried it with a WKT file as I have not found one that the program will accept.

This was highlighted trying to do an extract for UK.

**Comment by TimSC** [comment]
This might be something to do with the command line parsing of minus signs. I'm using boost program options. Can you put double quotes around the command?

   ./extract --bbox="[-1.0, 50.5, 1.0, 50.6]" --out=test_-1.0_50.5_1.0_50.6.osm.gz

Where did the square brackets come from? Did I do that? :)

**Comment by 4x4falcon** [comment]
Without the square brackets it works correctly with and without double quotes.

I thought it may have been like xapi requests for the bounding box so used the square brackets.

I'll close this.
